import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Nft from '#models/nft'
export default class extends BaseSeeder {
  async run() {
    await Nft.createMany([
      {
        link: 'ABJDIEKDJJDE',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/ABJDIEKDJJDE.jpg',
        price: 100,
      },
      {
        link: 'OAOOAOBBD',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/OAOOAOBBD.jpg',
        price: 250,
      },
      {
        link: 'BBBBAAAAAA',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/BBBBAAAAAA.jpg',
        price: 100,
      },
      {
        link: 'KKKKKKKKEEEV',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/KKKKKKKKEEEV.jpg',
        price: 250,
      },
      {
        link: 'MEEEEEEEETCS',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Lyon',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/MEEEEEEEETCS.jpg',
        price: 100,
      },
      {
        link: 'SKIIIAAOOOOO',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Lille',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/SKIIIAAOOOOO.jpg',
        price: 250,
      },
      {
        id: 7,
        link: 'AOODOKIJDJJFF',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/AOODOKIJDJJFF.jpg',
        price: 100,
      },
      {
        link: 'BAAAAASKKIEJD',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Angers',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/BAAAAASKKIEJD.jpg',
        price: 250,
      },
      {
        link: 'IDJRNJRJFJRJJRJF',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/IDJRNJRJFJRJJRJF.jpg',
        price: 100,
      },
      {
        link: 'OSOSKJDJJDJKR',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/OSOSKJDJJDJKR.jpg',
        price: 250,
      },
      {
        link: 'NDNDNNNEEJJDKEO',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/NDNDNNNEEJJDKEO.jpg',
        price: 100,
      },
      {
        link: 'JFJFJIROOFJKEOF',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/JFJFJIROOFJKEOF.jpg',
        price: 250,
      },
      {
        link: 'BBCBDBHEJEDJKCJEKK',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/BBCBDBHEJEDJKCJEKK.jpg',
        price: 100,
      },
      {
        link: 'KDKIKEIEDKDKEDRND',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/KDKIKEIEDKDKEDRND.jpg',
        price: 250,
      },
      {
        link: 'JDJJEJDJJEJJDJEJJDJJDJKD',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image:
          'https://instamintkami.blob.core.windows.net/instamint-nft/JDJJEJDJJEJJDJEJJDJJDJKD.jpg',
        price: 250,
      },
      {
        link: 'KJDKEKKEDKDKEKKDKDKKDK',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image:
          'https://instamintkami.blob.core.windows.net/instamint-nft/KJDKEKKEDKDKEKKDKDKKDK.jpg',
        price: 250,
      },
      {
        link: 'OSODJJBCHZJXUIEKXJLZKD',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image:
          'https://instamintkami.blob.core.windows.net/instamint-nft/OSODJJBCHZJXUIEKXJLZKD.jpg',
        price: 250,
      },
      {
        link: 'NDNXBBCHAKCIJEJCC',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/NDNXBBCHAKCIJEJCC.jpg',
        price: 250,
      },
      {
        link: 'AJEOCJLEPMXHGFURJGFUR',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image:
          'https://instamintkami.blob.core.windows.net/instamint-nft/AJEOCJLEPMXHGFURJGFUR.jpg',
        price: 250,
      },
      {
        link: 'JDHCGLAIOCJNEXKBCDJJNCKE',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image:
          'https://instamintkami.blob.core.windows.net/instamint-nft/JDHCGLAIOCJNEXKBCDJJNCKE.jpg',
        price: 250,
      },
      {
        link: 'AZCJJEJJDNEJNDKEEKKD',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/AZCJJEJJDNEJNDKEEKKD.jpg',
        price: 250,
      },
      {
        link: 'JJJJDJZKLAKJDOOZO',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image: 'https://instamintkami.blob.core.windows.net/instamint-nft/JJJJDJZKLAKJDOOZO.jpg',
        price: 250,
      },
      {
        link: 'KAKOZOKEBVINDKEKDLISLMEM',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image:
          'https://instamintkami.blob.core.windows.net/instamint-nft/KAKOZOKEBVINDKEKDLISLMEM.jpg',
        price: 250,
      },
      {
        link: 'AZJBCOLPALKDKKKKDKZPLKKED',
        description: 'This is a description',
        hashtags: '#hashtag1 #hashtag2 #hashtag3',
        place: 'Paris',
        draft: false,
        image:
          'https://instamintkami.blob.core.windows.net/instamint-nft/AZJBCOLPALKDKKKKDKZPLKKED.jpg',
        price: 250,
      },
    ])
  }
}
